#############################################################################
# Makefile for building: RestreamerFull
# Generated by qmake (2.01a) (Qt 4.7.4) on: Mon Jun 4 21:30:46 2012
# Project:  RestreamerFull.pro
# Template: subdirs
# Command: /home/raiv/QtSDK/Desktop/Qt/474/gcc/bin/qmake -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile RestreamerFull.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /home/raiv/QtSDK/Desktop/Qt/474/gcc/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-CuteLogger \
		sub-qHttpServer \
		sub-qtRestreamer

CuteLogger/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) CuteLogger/ || $(MKDIR) CuteLogger/ 
	cd CuteLogger/ && $(QMAKE) /home/raiv/QtProjects/RestreamerFull/CuteLogger/CuteLogger.pro -spec ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-CuteLogger-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) CuteLogger/ || $(MKDIR) CuteLogger/ 
	cd CuteLogger/ && $(QMAKE) /home/raiv/QtProjects/RestreamerFull/CuteLogger/CuteLogger.pro -spec ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-CuteLogger: CuteLogger/$(MAKEFILE) FORCE
	cd CuteLogger/ && $(MAKE) -f $(MAKEFILE)
sub-CuteLogger-make_default: CuteLogger/$(MAKEFILE) FORCE
	cd CuteLogger/ && $(MAKE) -f $(MAKEFILE) 
sub-CuteLogger-make_first: CuteLogger/$(MAKEFILE) FORCE
	cd CuteLogger/ && $(MAKE) -f $(MAKEFILE) first
sub-CuteLogger-all: CuteLogger/$(MAKEFILE) FORCE
	cd CuteLogger/ && $(MAKE) -f $(MAKEFILE) all
sub-CuteLogger-clean: CuteLogger/$(MAKEFILE) FORCE
	cd CuteLogger/ && $(MAKE) -f $(MAKEFILE) clean
sub-CuteLogger-distclean: CuteLogger/$(MAKEFILE) FORCE
	cd CuteLogger/ && $(MAKE) -f $(MAKEFILE) distclean
sub-CuteLogger-install_subtargets: CuteLogger/$(MAKEFILE) FORCE
	cd CuteLogger/ && $(MAKE) -f $(MAKEFILE) install
sub-CuteLogger-uninstall_subtargets: CuteLogger/$(MAKEFILE) FORCE
	cd CuteLogger/ && $(MAKE) -f $(MAKEFILE) uninstall
qHttpServer/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qHttpServer/ || $(MKDIR) qHttpServer/ 
	cd qHttpServer/ && $(QMAKE) /home/raiv/QtProjects/RestreamerFull/qHttpServer/qHttpServer.pro -spec ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-qHttpServer-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qHttpServer/ || $(MKDIR) qHttpServer/ 
	cd qHttpServer/ && $(QMAKE) /home/raiv/QtProjects/RestreamerFull/qHttpServer/qHttpServer.pro -spec ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-qHttpServer: qHttpServer/$(MAKEFILE) FORCE
	cd qHttpServer/ && $(MAKE) -f $(MAKEFILE)
sub-qHttpServer-make_default: qHttpServer/$(MAKEFILE) FORCE
	cd qHttpServer/ && $(MAKE) -f $(MAKEFILE) 
sub-qHttpServer-make_first: qHttpServer/$(MAKEFILE) FORCE
	cd qHttpServer/ && $(MAKE) -f $(MAKEFILE) first
sub-qHttpServer-all: qHttpServer/$(MAKEFILE) FORCE
	cd qHttpServer/ && $(MAKE) -f $(MAKEFILE) all
sub-qHttpServer-clean: qHttpServer/$(MAKEFILE) FORCE
	cd qHttpServer/ && $(MAKE) -f $(MAKEFILE) clean
sub-qHttpServer-distclean: qHttpServer/$(MAKEFILE) FORCE
	cd qHttpServer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qHttpServer-install_subtargets: qHttpServer/$(MAKEFILE) FORCE
	cd qHttpServer/ && $(MAKE) -f $(MAKEFILE) install
sub-qHttpServer-uninstall_subtargets: qHttpServer/$(MAKEFILE) FORCE
	cd qHttpServer/ && $(MAKE) -f $(MAKEFILE) uninstall
qtRestreamer/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qtRestreamer/ || $(MKDIR) qtRestreamer/ 
	cd qtRestreamer/ && $(QMAKE) /home/raiv/QtProjects/RestreamerFull/qtRestreamer/qtRestreamer.pro -spec ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-qtRestreamer-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qtRestreamer/ || $(MKDIR) qtRestreamer/ 
	cd qtRestreamer/ && $(QMAKE) /home/raiv/QtProjects/RestreamerFull/qtRestreamer/qtRestreamer.pro -spec ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-qtRestreamer: qtRestreamer/$(MAKEFILE) FORCE
	cd qtRestreamer/ && $(MAKE) -f $(MAKEFILE)
sub-qtRestreamer-make_default: qtRestreamer/$(MAKEFILE) FORCE
	cd qtRestreamer/ && $(MAKE) -f $(MAKEFILE) 
sub-qtRestreamer-make_first: qtRestreamer/$(MAKEFILE) FORCE
	cd qtRestreamer/ && $(MAKE) -f $(MAKEFILE) first
sub-qtRestreamer-all: qtRestreamer/$(MAKEFILE) FORCE
	cd qtRestreamer/ && $(MAKE) -f $(MAKEFILE) all
sub-qtRestreamer-clean: qtRestreamer/$(MAKEFILE) FORCE
	cd qtRestreamer/ && $(MAKE) -f $(MAKEFILE) clean
sub-qtRestreamer-distclean: qtRestreamer/$(MAKEFILE) FORCE
	cd qtRestreamer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qtRestreamer-install_subtargets: qtRestreamer/$(MAKEFILE) FORCE
	cd qtRestreamer/ && $(MAKE) -f $(MAKEFILE) install
sub-qtRestreamer-uninstall_subtargets: qtRestreamer/$(MAKEFILE) FORCE
	cd qtRestreamer/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: RestreamerFull.pro  ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++/qmake.conf ../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile RestreamerFull.pro
../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile RestreamerFull.pro

qmake_all: sub-CuteLogger-qmake_all sub-qHttpServer-qmake_all sub-qtRestreamer-qmake_all FORCE

make_default: sub-CuteLogger-make_default sub-qHttpServer-make_default sub-qtRestreamer-make_default FORCE
make_first: sub-CuteLogger-make_first sub-qHttpServer-make_first sub-qtRestreamer-make_first FORCE
all: sub-CuteLogger-all sub-qHttpServer-all sub-qtRestreamer-all FORCE
clean: sub-CuteLogger-clean sub-qHttpServer-clean sub-qtRestreamer-clean FORCE
distclean: sub-CuteLogger-distclean sub-qHttpServer-distclean sub-qtRestreamer-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-CuteLogger-install_subtargets sub-qHttpServer-install_subtargets sub-qtRestreamer-install_subtargets FORCE
uninstall_subtargets: sub-CuteLogger-uninstall_subtargets sub-qHttpServer-uninstall_subtargets sub-qtRestreamer-uninstall_subtargets FORCE

sub-CuteLogger-check: CuteLogger/$(MAKEFILE)
	cd CuteLogger/ && $(MAKE) check
sub-qHttpServer-check: qHttpServer/$(MAKEFILE)
	cd qHttpServer/ && $(MAKE) check
sub-qtRestreamer-check: qtRestreamer/$(MAKEFILE)
	cd qtRestreamer/ && $(MAKE) check
check: sub-CuteLogger-check sub-qHttpServer-check sub-qtRestreamer-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

